//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBase.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Misa.Web05.Core.Resources.ExceptionErrorMessage", typeof(ExceptionErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không thể lớn hơn ngày hiện tại.
        /// </summary>
        public static string DateOfBirthBiggerThanCurrentDate {
            get {
                return ResourceManager.GetString("DateOfBirthBiggerThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban đã tồn tại.
        /// </summary>
        public static string DepartmentIdExists {
            get {
                return ResourceManager.GetString("DepartmentIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được trống.
        /// </summary>
        public static string DepartmentIdNull {
            get {
                return ResourceManager.GetString("DepartmentIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được trống.
        /// </summary>
        public static string DepartmentNameNull {
            get {
                return ResourceManager.GetString("DepartmentNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống.
        /// </summary>
        public static string DevMessage400 {
            get {
                return ResourceManager.GetString("DevMessage400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống.
        /// </summary>
        public static string DevMessage500 {
            get {
                return ResourceManager.GetString("DevMessage500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên &amp;lt;{0}&amp;gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string EmployeeCodeExists {
            get {
                return ResourceManager.GetString("EmployeeCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code nhân viên không hợp lệ.
        /// </summary>
        public static string EmployeeCodeInvalid {
            get {
                return ResourceManager.GetString("EmployeeCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code nhân viên không được trống.
        /// </summary>
        public static string EmployeeCodeNull {
            get {
                return ResourceManager.GetString("EmployeeCodeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string EmployeeIdExists {
            get {
                return ResourceManager.GetString("EmployeeIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trống.
        /// </summary>
        public static string EmployeeIdNull {
            get {
                return ResourceManager.GetString("EmployeeIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được trống.
        /// </summary>
        public static string FullNameNull {
            get {
                return ResourceManager.GetString("FullNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp chứng minh nhân dân không thể lớn hơn ngày hiện tại.
        /// </summary>
        public static string IdentityDateBiggerThanCurrentDate {
            get {
                return ResourceManager.GetString("IdentityDateBiggerThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí  đã tồn tại.
        /// </summary>
        public static string PositionIdExists {
            get {
                return ResourceManager.GetString("PositionIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vị trí không được trống.
        /// </summary>
        public static string PositionIdNull {
            get {
                return ResourceManager.GetString("PositionIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí không được trống.
        /// </summary>
        public static string PositionNameNull {
            get {
                return ResourceManager.GetString("PositionNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string UserMessage400 {
            get {
                return ResourceManager.GetString("UserMessage400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra với hệ thống, vui lòng thử lại sau.
        /// </summary>
        public static string UserMessage500 {
            get {
                return ResourceManager.GetString("UserMessage500", resourceCulture);
            }
        }
    }
}
